Fix kmod rpm install failed
Fix kmod rpm install failed which built via macro kernel_module_package.

Remove "%global _use_internal_dependency_generator 0" to workaround
below install dependency error, because current kernel rpm doesn't
provide kernel symbols.
"nothing provides kernel(xx) .. needed by kmod-.."
See issue:
https://gitee.com/src-openeuler/openEuler-rpm-config/issues/I6NR1U

Use path "/usr/sbin/depmod" instead of "/sbin/depmod" to fix install
error: "nothing provides /sbin/depmod needed by kmod-xx".

Remove "echo "/lib/firmware/"" to fix below build error:
"error: Directory not found: /xx/BUILDROOT/xxx/lib/firmware"

Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>
(cherry picked from commit 290861e7bc398eb437d72d3f456e7f0b2fea5bfc)